parameters:
    test_fixture_image_dir: '%kernel.project_dir%%env(TEST_FIXTURE_IMAGE_DIR)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Tests\Resource\Fixture\:
        resource: '%kernel.project_dir%/tests/Resource/Fixture'
        tags:
          - { "name": "doctrine.fixture.orm" }

    App\Shared\Infrastructure\Bus\CommandBus:
        public: true

    App\Shared\Infrastructure\Bus\QueryBus:
        public: true

    App\Tests\Resource\Fixture\Product\ProductImageFixture:
        arguments:
            $testFixtureImageDir: '%env(TEST_FIXTURE_IMAGE_DIR)%'
